config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, controllers:{
    sessions: 'admins/sessions'
  }

  devise_for :end_users, controllers:{
    registrations: 'publics/registrations',
    sessions: 'publics/sessions'
  }

  namespace :admin do
    root 'homes#top'
    resources :items, only: [:index, :new, :create]
    #いらないかもしれないからshow edit updateはresourcesの中から以下に記述
    get "/items/:id"  => "items#show"
    get "/items/:id/edit"  => "items#edit"
    patch "/items/:id"  => "items#update"
    resources :genres, only: [:index, :create, :edit, :update]
    resources :end_users, only: [:index, :show, :edit, :update]
    #admin/orders
    resources :orders, only: [:show,:update]
    #admin/order_details
    resources :order_details, only: [:update]

  end

  scope module: :public do
    #コントローラ名
    #public/homes
    root 'homes#top'
    #public/items
    resources :items, only: [:index, :show]
    #public/end_users
    get  "end_users/mypage"  => "end_users#mypage"
    get  "/end_users/confirm" => "end_users#confirm"
    resource :end_users, only: [:edit, :update]
    patch '/withdraw' => 'end_users#withdraw', as: 'withdraw_end_user'
    put '/withdraw/' => 'end_users#withdraw'
    #public/cart_items
    resources :cart_items, only: [:index, :create, :update, :destroy]
    delete '/cart_items' => 'cart_items#destroy_all', as: 'destroy_all_cart_items'
    #public/orders
    resources :orders, only: [:index, :new, :create]
    post '/orders/confirm' => 'orders#confirm'
    get '/orders/complete' => 'orders#complete'
    get '/orders/:id' => 'orders#show'
    #public/addresses
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :end_user

  def full_address
    self.postal_code + self.address + self.name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :end_user
  belongs_to :item
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items
  has_many :orders
  has_many :addresses

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_name_kana, presence: true
  validates :last_name_kana, presence: true
  validates :address, presence: true
  validates :postal_code, presence: true
  validates :phone_number, presence: true

  def full_name
    self.first_name + self.last_name
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items
  has_many :orders
  attachment :image
  def self.search(search)
    if search
      Item.where(['name LIKE ?', "%#{search}%"])
    else
      Item.all
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :end_user
  has_many :order_details

  enum payment_method: { bank_transfer: 0, credit: 1 }
  enum sales_order_status: { wating_for_payment: 0, confirmation_of_payment: 1, in_production: 2, preparing_to_ship: 3, shipped: 4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  enum production_status: { not_startable: 0, wating_for_production: 1, under_production: 2, production_completed: 3 }
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genres = Genre.all
    @genre =Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path, notice: "You have created book successfully."
    else
      @genres = Genre.all
      render 'index'
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path, notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    # @items = Item.all
    # Item.rbに上記を記述
    @items = Item.search(params[:search])
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item), notice: "You have created book successfully."
    else
      @items = Item.all
      render 'new'
    end
  end

  def search
    @items = Item.search(params[:search])
  end

  def show
  end

  def edit
  end

  def update
  end

  private

  def item_params
    params.require(:item).permit(:name, :description, :tax_excluded_price, :is_active, :image, :genre_id)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    # ①注文ステータスが 入金確認 → 全ての製作ステータスを 製作待ち
    if @order.sales_order_status == "confirmation_of_payment"
      # @order.order_details.each do |order_detail|
      @order.order_details.update(production_status: 1)
    end
    # ②製作ステータスが一つでも 製作中 → 注文ステータスを 製作中
      #params[:production_status] が”製作中”
    # ③製作ステータスが全て 製作完了 → 注文ステータスを 発送準備中
    redirect_to admin_order_path(@order)
  end

  private

  def order_params
    params.require(:order).permit(:postal_code, :name, :address, :payment_method, :shipping_cost, :end_user_id, :sales_order_status, :billing_amount)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    root_path # ログイン後に遷移するpathを設定
  end

  def after_sign_out_path_for(resource)
    root_path # ログアウト後に遷移するpathを設定
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email,:first_name,:last_name,:first_name_kana,:last_name_kana,:address,:postal_code,:phone_number])
    devise_parameter_sanitizer.permit(:account_update, keys: [:email,:first_name,:last_name,:first_name_kana,:last_name_kana,:address,:postal_code,:phone_number])
  end
end

app/helpers/admin/end_users_helper.rb
module Admin::EndUsersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/end_users_helper.rb
module EndUsersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/genres/edit.html.erb
<%= form_with model: @genre, url: "/admin/genres/#{@genre.id}", local:true do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/admin/genres/index.html.erb
<%= form_with model: @genre, url: "/admin/genres", local:true do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

<% @genres.each do |g| %>
<div>
  <%= g.name %>
  <%= link_to '編集', edit_admin_genre_path(g) %>
</div>
<% end %>

app/views/admin/homes/top.html.erb
<% @orders.each do |o| %>

  <%= link_to o.created_at.to_s(:datetime_jp), admin_order_path(o.id)  %><br>
  <%#= xxx.updated_at.to_s(:datetime_jp) %>
  購入者：<%= o.end_user.full_name %><br>

  <% amount = 0 %>
  <% o.order_details.each do |order_detail|%>
    <% amount += order_detail.quantity %>
  <% end %>
  注文個数：<%= amount %>個<br>
  注文ステータス：<%= o.sales_order_status_i18n %><br>

<% end %>

app/views/admin/items/edit.html.erb
<h1>Admin::Items#edit</h1>
<p>Find me in app/views/admin/items/edit.html.erb</p>

app/views/admin/items/index.html.erb
<% @items.each do |i| %>
<div>
  <%= i.id %>
  <%= i.name %>
  <%= i.tax_excluded_price %>
  <%= i.genre.name %>
  <%if i.is_active %>
   販売中
  <% else %>
   販売停止中
  <% end %>
</div>
<% end %>
<%= link_to '商品新規登録', new_admin_item_path %>

app/views/admin/items/new.html.erb
<%= form_with model: @item, url: "/admin/items", local:true do |f| %>
    <%= f.label :商品名 %>
    <%= f.text_field :name %>
    <%= f.label :商品説明 %>
    <%= f.text_field :description %>
    <%= f.label :値段 %>
    <%= f.text_field :tax_excluded_price %>
    <div>
      <%= f.label :販売ステータス %>
      <%= f.radio_button :is_active, true %>
      <%= f.label :is_active, '販売中', value: true %>
      <%= f.radio_button :is_active, false %>
      <%= f.label :is_active, '販売停止中', value: false %>
    </div>
    <%= f.attachment_field :image %>
    <%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "選択して下さい" %>

  <%= f.submit %>
<% end %>

app/views/admin/items/show.html.erb
<h1>Admin::Items#show</h1>
<p>Find me in app/views/admin/items/show.html.erb</p>

app/views/admin/orders/show.html.erb
購入者：<%= @order.end_user.full_name %><br>
注文日：<%= @order.created_at.to_s(:datetime_jp)%><br>
配送先：<%= @order.postal_code %><%= @order.address %><%= @order.name %><br>
支払い方法：<%= @order.payment_method_i18n %><br>

<%= form_with model: @order, url: "/admin/orders/#{@order.id}", local:true, method: :patch do |f| %>
    注文ステータス：<%= f.select :sales_order_status, Order.sales_order_statuses_i18n.keys.map{|k| [I18n.t("enums.order.sales_order_status.#{k}"), k]} %>

    <%= f.submit %>
<% end %>

<br>＜注文商品＞<br>
<% @order_sum = 0 %>
<% @order.order_details.each do |order_detail|%>
    商品名：<%= order_detail.item.name %><br>
    単価（税込）<%= order_detail.tax_included_price %><br>
    注文個数：<%= order_detail.quantity %><br>
    小計：<%= order_detail.tax_included_price*order_detail.quantity %><br>
    <% @order_sum += order_detail.tax_included_price*order_detail.quantity %>
    <%= form_with model: order_detail, url: "/admin/order_details/#{order_detail.id}", local:true, method: :patch do |f| %>
        制作ステータス：<%= f.select :production_status, OrderDetail.production_statuses_i18n.keys.map{|k| [I18n.t("enums.order_detail.production_status.#{k}"), k]} %>
        <%= f.submit %>
    <% end %>

============================<br>
<% end %>
商品合計：<%= @order_sum %>円<br>
送料：<%= @order.shipping_cost %><br>
請求額：<%= @order.billing_amount %><br>